<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class NormalUserSeeder extends Seeder
{
    /**
     * A non-admin user for testing the public /api/login + api-key flows
     * (connect/execute), as opposed to AdminUserSeeder's admin-panel user.
     */
    public function run(): void
    {
        $user = User::firstOrCreate(
            ['email' => 'user@app.com'],
            [
                'name'     => 'Demo User',
                'password' => Hash::make('password'),
                'phone'    => '01000000001',
            ]
        );

        // Overrides the api_key auto-generated by User::booted() with a fixed,
        // known value for easy local testing.
        $user->apiKey()->updateOrCreate(
            ['user_id' => $user->id],
            ['key' => 'dev_user_api_key_3e7b1c9a4f6d2058b1a3c9e7d4f6a208']
        );
    }
}
