<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Integration;
use App\Models\IntegrationAuthStep;
use App\Models\IntegrationHeader;

class PaymobIntegrationSeeder extends Seeder
{
    public function run(): void
    {
        // 1. Core Integration Setup
        $integration = Integration::create([
            'name'              => 'Paymob',
            'base_api_url'      => 'https://accept.paymob.com/api',
            'documentation_url' => 'https://developers.paymob.com',
            'description_en'    => 'Accept payments in your store through Paymob.',
            'description_ar'    => 'استقبل مدفوعات متجرك عن طريق باي موب.',
            'publish'           => true,
            'category'          => 'payment',
        ]);

        // 2. Global Integration Headers — every service call sends the auth
        //    token generated by the set_credentials step below.
        IntegrationHeader::create([
            'integration_id' => $integration->id,
            'type'           => 'bearer',
            'header_key'     => 'Authorization',
            'require_from'   => 'user_integration',
            'value'          => 'token',
            'label'          => 'Paymob Auth Token',
            'is_active'      => true,
            'order'          => 1,
        ]);

        // 3. Auth Steps — single set_credentials step (docs.paymob.com "Authentication
        //    Request (Generate Auth Token)"). The admin/merchant supplies their
        //    permanent secret API Key, and this call exchanges it for a short-lived
        //    auth token used to authenticate every other Paymob API call.
        IntegrationAuthStep::create([
            'integration_id'    => $integration->id,
            'name'              => 'Generate Auth Token',
            'step_type'         => 'set_credentials',
            'auth_type'         => 'call',
            'http_method'       => 'POST',
            'base_endpoint_url' => 'https://accept.paymob.com/api/auth/tokens',
            'inputs'            => [
                [
                    'key'          => 'api_key',
                    'label'        => 'API Key',
                    'type'         => 'body',
                    'require_from' => 'user',
                ],
            ],
            'outputs'           => ['token'],
            'response_example'  => [
                'token'   => 'ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5...',
                'profile' => [
                    'id'         => 12345,
                    'user'       => ['username' => 'merchant_1'],
                    'created_at' => '2026-01-10T10:00:00Z',
                ],
                'id' => 12345,
            ],
            'order'             => 1,
            'is_active'         => true,
        ]);
    }
}
